### ISSUE TITLE
Make the `constant` extension more flexible

### ISSUE THREAD

**Issue by Maksimka101** [purplenoodlesoop/pure#5]
Hello

I suggest you to change the `constant` extension from `A constant(dynamic _) => this;` to `A constant([dynamic _, dynamic __, dynamic ___, dynamic ___, ....]) => this;`. It will make this extension much more flexible and usable. For example, in flutter's `IndexedWidgetBuilder`s like separator builder

**Comment by purplenoodlesoop** [comment]
Added in #9
