### ISSUE TITLE
Missing extension Apply1X

### ISSUE THREAD

**Issue by miklcct** [purplenoodlesoop/pure#6]
Calling `.apply(x)` on a one-argument function should produce a zero-argument function, in the same way that calling `.apply(x)` on an N+1-argument function should produce an N-argument function.

```dart
/// {@macro extensions.curry}
extension Apply1X<A, T> on F1<A, T> {
  /// {@macro extensions.partial_application}
  F0<T> apply(A a) => () => this(a);
}
```

**Comment by purplenoodlesoop** [comment]
Added in #9 via `thunk` extension
